<?php
$canViewCustomers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'));
$canViewUsers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('user'));
?>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-12">
                <h1 style="position: relative; top: 5px">
                    <i class="fas fa-home"></i>
                    Início
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content" style="margin-left: 9px; margin-right: 9px;">
    <div class="container-fluid">
        <div class="row">
            <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewCustomers): ?>
                <div class="col-lg-6 col-6">
                    <div class="small-box bg-primary" onclick="openModule('clientes')" style="cursor: pointer;">
                        <div class="inner">
                            <p>Clientes</p>
                            <h3><?php echo $this->view->total_customers; ?></h3>
                        </div>
                        <div class="icon">
                            <i class="fas fa-users text-white"></i>
                        </div>
                        <a  class="small-box-footer" style="cursor: pointer;">
                            Mais informações <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewUsers): ?>
                <div class="col-lg-6 col-6">
                    <div class="small-box bg-primary" onclick="openModule('usuarios')" style="cursor: pointer;">
                        <div class="inner">
                            <p>Colaboradores</p>
                            <h3><?php echo $this->view->total_users; ?></h3>
                        </div>
                        <div class="icon">
                            <i class="fas fa-users-cog text-white"></i>
                        </div>
                        <a class="small-box-footer" style="cursor: pointer;">
                            Mais informações <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>