<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-12">
                <h1 style="position: relative; top: 5px">
                    <i class="fas fa-home"></i>
                    Início
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content" style="margin-left: 9px; margin-right: 9px;">
    <div class="container-fluid">
        <div class="row">
            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 1, 1)): ?>
                <!-- ./col -->
                <div class="col-lg-6 col-6">
                    <!-- small box -->
                    <div class="small-box bg-primary">
                        <div class="inner">
                        <h3><?php echo $this->view->total_users; ?></h3>

                        <p>Usuários</p>
                        </div>
                        <div class="icon">
                        <i class="fas fa-users"></i>
                        </div>
                        <a onclick="openModule('clientes')" class="small-box-footer" style="cursor: pointer;">
                            Mais informações <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 1, 6)): ?>
                <!-- ./col -->
                <div class="col-lg-6 col-6">
                    <!-- small box -->
                    <div class="small-box bg-primary">
                        <div class="inner">
                        <h3><?php echo $this->view->total_users; ?></h3>

                        <p>Clientes</p>
                        </div>
                        <div class="icon">
                        <i class="fas fa-users"></i>
                        </div>
                        <a onclick="openModule('clientes')" class="small-box-footer" style="cursor: pointer;">
                            Mais informações <i class="fas fa-arrow-circle-right"></i>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
            <!-- ./col -->
        </div>
    </div>
</section>