<?php 
$config = $this->getSiteConfig();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Alterar Senha | <?php echo $config['site_title']; ?></title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" type="image/x-icon" />

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/dist/css/adminlte.min.css">

    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <style>
        h1 {
            color: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }
    </style>
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-dark">
            <div class="card-header text-center">
                <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo" style="width: 100%;">
            </div>
            <div class="card-body">
                <p class="login-box-msg">Defina a nova senha</p>
              
                
                <form action="<?php echo baseUrl; ?>alterar-senha" method="post" onsubmit="hashPass(this);">
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Senha" name="password" required minlength="8" maxlength="100">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Confirme a senha" name="confirmation" required minlength="8" maxlength="100">
                        <div class="input-group-append">
                            <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        <input type="hidden" name="info" value="<?php echo $this->view->code; ?>">
                    </div>
                    <div class="row">
                        <div class="col-12 mt-1">
                            <button type="submit" class="btn btn-primary btn-block">Confirmar</button>
                        </div>
                        <div class="col-12 text-center mt-2">
                            <a href="<?php echo baseUrl; ?>" style=" color: #000;">
                                Voltar
                            </a>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE Admin -->
    <script src="<?php echo baseUrl; ?>public/app/dist/js/adminlte.min.js"></script>

    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/alerts.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
    <script>
        function hashPass(form) {
            if (form.password.value != '') {
                let psw = md5(form.password.value);
                form.password.value = psw;
            }

            if (form.confirmation.value != '') {
                let pswc = md5(form.confirmation.value);
                form.confirmation.value = pswc;
            }
        }
    </script>
    <?php if (!empty($this->view->errorPasswords)): ?>
        <script>
            showAlert('error', 'Ops!', '<?php echo $this->view->errorPasswords; ?>', 'top-center');
        </script>
    <?php endif; ?>
</html>
