<?php 
$data = $this->view->data; 
?>
<?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-9">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-user"></i>
                        <?php echo $this->view->role['name']; ?> - Permissões
                    </h1>
                </div>
                <div class="col-3">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-primary btn-flat"
                                onclick="openDetails('<?php echo $this->view->role['uuid']; ?>');">
                                <i class="fas fa-arrow-left pr-1"></i> Voltar
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_role2" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center bg-primary">
                                        <th class="text-white" style="font-size: 14px;">Recurso</th>
                                            <th class="text-white" style="font-size: 14px;">Módulo</th>
                                            <th class="text-white" style="font-size: 14px;">Ativo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center">
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['resource']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['module']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <input type="checkbox" id="my-checkbox-<?php echo $entity['uuid']; ?>"
                                                        data-bootstrap-switch data-off-color="danger" 
                                                        data-on-color="success" onchange="getVal('<?php echo $entity['uuid']; ?>');"
                                                        <?php echo ($entity['status'] == 1) ? 'checked' : ''; ?>>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function(){
            $("input[data-bootstrap-switch]").each(function(){
                $(this).bootstrapSwitch();
            });
       
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data, row, column, node ) {
                            return data;
                        }
                    }
                }
            };	

            $('#table_role2').DataTable({
                "sDom": 'fltip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'PRIVILÉGIOS DE ACESSO',
                        exportOptions: {columns: [0,1]}
                    }), 
                    {extend: 'pdf', 
                        title: 'PRIVILÉGIOS DE ACESSO',
                        orientation: 'landscape',
                        pageSize: 'LEGAL',
                        exportOptions: {columns: [0,1]}
                    }
                ],
                order: [ [1, "asc"] ],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 10,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function getVal(uuid) {
            let status_acl = "";
            if ($('#my-checkbox-' + uuid).is(":checked")) {
                status_acl = 1;    
            } else {
                status_acl = 0;
            }
            
            $("#baseLoader").show();
        
            $.ajax({
                type: "POST",
                url: "<?php echo baseUrl; ?>controle-acesso/altera-permissao",
                data: {
                    uuid: uuid,
                    status: status_acl
                },
                dataType: 'json',
                async: true
            }).done(function(data) {
                showAlert(data.type, data.title, data.msg, data.pos);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert(); 
                $("#baseLoader").hide();   
            }); 
        }
    </script>
<?php endif; ?>