<?php 
$config = $this->getSiteConfig();

$canViewCustomers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('customers'));
$canViewUsers = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('user'));
$canViewConfigs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('configs'));
$canViewPolitics = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('politics'));
$canViewLogs = $this->acl($_SESSION['ROLE'], $this->resourceCodes('view'), $this->moduleCodes('logs'));

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $config['site_title']; ?></title>
    <meta author="João Augusto Bonfante">
    <link rel="icon" href="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" type="image/x-icon" />

    <!-- CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/dist/css/adminlte.css">
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">

    <link href="<?php echo baseUrl; ?>public/app/css/buttons.dataTables.min.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/css/dataTables.bootstrap4.min.css">

    <!-- JS -->
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery/jquery.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/dist/js/adminlte.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/jquery.maskMoney.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jquery.maskedinput.js" type="text/javascript"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jquery.validate.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/jquery.inputmask.js"></script>
    <link rel="stylesheet" href="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.css">
    <script src="<?php echo baseUrl; ?>public/app/plugins/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/alerts.js"></script>

    <script src="<?php echo baseUrl; ?>public/app/js/jquery.dataTables.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/dataTables.bootstrap4.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/date-eu.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/date-eu-com-filtro.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/dataTables.valoremreais.js"></script>
    <script src="<?php echo baseUrl; ?>public/app/js/dataTables.buttons.min.js"></script>
   
	<script src="<?php echo baseUrl; ?>public/app/js/jszip.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/pdfmake.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/vfs_fonts.js"></script>
 
	<script src="<?php echo baseUrl; ?>public/app/js/buttons.html5.min.js"></script>
	<script src="<?php echo baseUrl; ?>public/app/js/buttons.print.min.js"></script>

    <script src="<?php echo baseUrl; ?>public/app/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>

    $.widget.bridge('uibutton', $.ui.button)
    </script>
    <style>
        .pst {
            position: relative;
            top: -3px;
        }

        h1 {
            color: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .bg-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .bg-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary {
            background: <?php echo $config['primary_color']; ?> !important;
        }

        .btn-primary:hover {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary {
            background: <?php echo $config['secondary_color']; ?> !important;
        }

        .btn-secondary:hover {
            background: <?php echo $config['primary_color']; ?> !important;
        }
        
        .page-link:hover {
            z-index: 2;
            color: #fff;
            text-decoration: none;
            background-color: <?php echo $config['secondary_color']; ?>;
            border-color: <?php echo $config['secondary_color']; ?>;
        }


        .page-item.active .page-link {
            z-index: 3;
            color: #fff;
            background-color: <?php echo $config['primary_color']; ?> !important;;
            border-color: <?php echo $config['primary_color']; ?> !important;;
        }
    </style>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo_icon']; ?>" 
        alt="<?php echo $config['site_title']; ?>" height="200">
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link"  href="<?php echo baseUrl . 'sair' ?>" >
                    Sair
                </a>
            </li>   
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color: <?php echo $config['primary_color']; ?> !important;">
        <!-- Brand Logo -->
        <a href="<?php echo baseUrl; ?>">
            <img src="<?php echo baseUrl . 'public/uploads/logo/' . $config['logo']; ?>" alt="logo" style="width: 100%;">
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="border-bottom: 1px solid white;">
            <div class="image">
            <?php if (!empty($_SESSION['PHOTO'])): ?>
                <img src="<?php echo baseUrl . 'public/uploads/users/' . $_SESSION['PHOTO']; ?>" class="img-circle elevation-2" alt="<?php echo $_SESSION['NAME']; ?>"
                    style="width: 46px; height: 46px;">
            <?php else: ?>
                <img src="<?php echo baseUrl; ?>public/app/dist/img/avatar5.png" class="img-circle elevation-2" alt="avatar"
                    style="width: 40px;">
            <?php endif; ?>
            </div>
            <div class="info" style="margin-top: -10px;">
                <a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer"><?php echo $_SESSION['NAME']; ?><br>
                <small><a onclick="openModule('meu-perfil');" class="d-block text-white" style="cursor: pointer">(<?php echo $_SESSION['ROLE_NAME']; ?>)</a></small></a>
                
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
                <li class="nav-item">
                    <a href="<?php echo baseUrl; ?>" class="nav-link text-white">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Início
                        </p>
                    </a>
                </li>    
                <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewCustomers): ?>
                    <li class="nav-item">
                        <a onclick="openModule('clientes');" class="nav-link text-white" style="cursor: pointer;" id="box_clientes">
                            <i class="nav-icon fas fa-users"></i>
                            <p>Clientes</p>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if (
                        $_SESSION['ROLE_ADM'] == '1' 
                        || $canViewUsers
                        || $canViewConfigs
                        || $canViewLogs
                        || $canViewPolitics
                    ): ?>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-white">
                            <i class="nav-icon fas fa-cog"></i>
                            <p>
                                SISTEMA
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview" style="display: none;">                 
                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewConfigs): ?>
                                <li class="nav-item ml-2">
                                    <a onclick="openModule('configuracoes');" class="nav-link text-white" style="cursor: pointer;">
                                        <i class="nav-icon fas fa-cogs"></i>
                                        <p>
                                            Configurações
                                        </p>
                                    </a>
                                </li>
                            <?php endif; ?>     
                            <?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
                                <li class="nav-item ml-2">
                                    <a onclick="openModule('controle-acesso');" class="nav-link text-white" style="cursor: pointer;">
                                        <i class="nav-icon fas fa-lock"></i>
                                        <p>
                                        Controle de Acesso
                                        </p>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewLogs): ?>
                                <li class="nav-item ml-2">
                                    <a onclick="openModule('logs');" class="nav-link text-white" style="cursor: pointer;">
                                        <i class="nav-icon fas fa-list"></i>
                                        <p>
                                            Logs 
                                        </p>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewPolitics): ?>
                                <li class="nav-item ml-2">
                                    <a onclick="openModule('politica-privacidade');" class="nav-link text-white" style="cursor: pointer;">
                                        <i class="nav-icon fas fa-eye"></i>
                                        <p>
                                            Política de Privacidade
                                        </p>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_SESSION['ROLE_ADM'] == '1' || $canViewUsers): ?>
                                <li class="nav-item ml-2">
                                    <a onclick="openModule('usuarios');" class="nav-link text-white" style="cursor: pointer;">
                                        <i class="nav-icon fas fa-user-cog"></i>
                                        <p>
                                            Colaboradores 
                                        </p>
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        
        <!-- Content -->
        <div id="sis_content">
            <?php echo $this->content(); ?>

        </div>
        
        <!-- Modal Mid -->
        <div class="modal fade" id="modalMid" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="overlay" id="modalMidLoader">
                        <i class="fas fa-2x fa-sync fa-spin"></i>
                    </div>
                    <div class="modal-header text-white bg-primary">
                        <h4 class="modal-title" id="modalMidTitle"></h4>
                        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="modalMidResult"></div>
                </div>
            </div>
        </div>

        
        
        <!-- Modal XL -->
        <div class="modal fade" id="modalXL" >
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="overlay" id="modalXLLoader">
                        <i class="fas fa-2x fa-sync fa-spin"></i>
                    </div>
                    <div class="modal-header bg-primary text-white">
                        <h4 class="modal-title" id="modalXLTitle"></h4>
                        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="modalXLResult"></div>
                </div>
            </div>
        </div>

        <!-- Modal Large -->
        <div class="modal fade" id="modalLarge" data-keyboard="false">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="overlay" id="modalLargeLoader">
                        <i class="fas fa-2x fa-sync fa-spin"></i>
                    </div>
                    <div class="modal-header text-white bg-primary">
                        <h4 class="modal-title" id="modalLargeTitle"></h4>
                        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="modalLargeResult"></div>
                </div>
            </div>
        </div>

                
        <!-- Modal Delete -->
        <div class="modal fade" id="modalDelete" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="overlay" id="modalDeleteLoader">
                        <i class="fas fa-2x fa-sync fa-spin"></i>
                    </div>
                    <div class="modal-header text-white bg-primary">
                        <h4 class="modal-title" id="modalDeleteTitle"></h4>
                        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="text-center pt-3">
                        <b>Tem certeza que deseja excluir este registro? <br>Após esta operação, não será possível revertê-la.</b>
                    </div>
                    <div class="modal-body text-center" id="modalDeleteResult"></div>
                </div>
            </div>
        </div>


        <div class="overlay-wrapper" id="baseLoader" style="display: none;">
            <div class="overlay">
                <i class="fas fa-3x fa-sync-alt fa-spin"></i>
                <div class="text-bold pt-2 ml-3">Carregando...</div>
            </div>
        </div>
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>&copy; <?php echo date('Y'); ?> <?php echo $config['site_title']; ?></strong>
        
        <div class="float-right d-none d-sm-inline-block">
        <b>Versão</b> 1.0.0
        </div>
    </footer>
    </div>
    <!-- ./wrapper -->

    <!-- AdminLTE for demo purposes -->

    <script>
        function openModule(urlParam) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>" + urlParam,
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }
    </script>
</body>
</html>
