<?php 
$data    = $this->view->data; 
$isAdmin = ($_SESSION['ROLE_ADM'] == '1') ? true : false;
$role    = $_SESSION['ROLE'];

$canView    = ($isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('user'))) ? true : false;
$canCreate  = ($isAdmin || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('user'))) ? true : false;
$canUpdate  = ($isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('user'))) ? true : false;
$canDelete  = ($isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('user'))) ? true : false;
$canViewAcl = ($isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('privileges'))) ? true : false;
?>
<?php if ($canView): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-6">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-user-cog pr-1"></i>
                        Colaboradores
                    </h1> 
                </div>
                <div class="col-6">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-primary btn-flat"
                                    onclick="createUser();" style="position: relative; top: 3px">
                                    <i class="fas fa-plus pr-1"></i> Adicionar
                                </button>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_user" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center bg-primary">
                                            <th class="text-white" style="font-size: 14px; ">Nome</th>
                                            <th class="text-white" style="font-size: 14px;">Email</th>
                                            <th class="text-white" style="font-size: 14px;">Celular</th>
                                            <th class="text-white" style="font-size: 14px;">Cargo</th>
                                            <th class="text-white" style="font-size: 14px;">Perfil</th>
                                            <th class="text-white" style="font-size: 14px;">Status</th>
                                            <th style="display: none;">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;" 
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px; ">
                                                    <?php echo $entity['name']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['email']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['cellphone']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['job_role']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['role']; ?>
                                                </td>
                                                <td>
                                                    <?php if ($entity['status'] == '1'): ?>
                                                        <i class="fa fa-circle" style="color: green;"></i>
                                                    <?php else: ?>
                                                        <i class="fa fa-circle" style="color: red;"></i>
                                                    <?php endif; ?>
                                                </td>  
                                                <td style="display: none;">
                                                    <?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?>
                                                </td> 
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data, row, column, node ) {
                            return data;
                        }
                    }
                }
            };	

            $('#table_user').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'USUÁRIOS',
                        exportOptions: {columns: [0,1,2,3,4,6]}
                    })
                ],
                order: [ [4, "asc"] ],
                columnDefs: [{orderable: false, targets: [5]}],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "usuarios/detalhes",
                data: {uuid:uuid},
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

    </script>
    <?php if ($canCreate): ?>
        <script>
            function createUser() {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "usuarios/cadastrar",
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateUser(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "usuarios/editar",
                    data: {uuid:uuid},
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteUser(uuid) {
                $("#modalXL").modal('hide');
                $("#modalDeleteResult").empty();
                $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Remover Usuário');
                $("#modalDeleteLoader").hide();
                $("#modalDelete").modal('show');
                $("#modalDeleteResult").html('<button type="button" class="btn btn-default" onclick="runDelete(\''+uuid+'\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
            }   

            function runDelete(uuid) {
                if (uuid !== null || uuid !== undefined) {
                    $("#modalDeleteLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "usuarios/excluir",
                        data: {uuid: uuid},
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalDelete").modal('hide');
                        $("#modalXL").modal('hide');
                        openModule('usuarios');
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalDeleteLoader").hide();
                    });
                }
            }
        </script>
    <?php endif; ?>
    <?php if ($canViewAcl): ?>
        <script>
            function aclUser(uuid) {
                $("#baseLoader").show();
                $.ajax({
                    type: 'post',
                    url: "usuarios/acl",
                    data: {uuid:uuid},
                    async: true
                }).done(function(data) {
                    $("#sis_content").html(data);
                    $("#baseLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#baseLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
<?php endif; ?>