<?php 
$entity = $this->view->entity; 
$roles = $this->view->roles; 
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('user'))): ?>
    <form method="post" name="formUpdateUser" id="formUpdateUser" onsubmit="hashPass(this);">
        <div class="row">
            <div class="col-md-12 bg-primary mb-3" style="border-radius: 5px;">
                <h4 class="pt-2 text-center">Dados Pessoais</h4>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" name="name" id="name" required
                        value="<?php echo $entity['name']; ?>" maxlength="100">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="cnpj">CPF</label>
                    <input type="text" class="form-control" name="document_1" id="document_1"  maxlength="14"
                        value="<?php echo $entity['document_1']; ?>" onchange="validateCPF();">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="cnpj">CNPJ</label>
                    <input type="text" class="form-control" name="document_2" id="document_2"  maxlength="18"
                        value="<?php echo $entity['document_2']; ?>" onchange="validateCNPJ();">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="job_role">Cargo</label>
                    <input type="text" class="form-control" name="job_role" id="job_role" required
                        value="<?php echo $entity['job_role']; ?>" maxlength="50">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Nível de Acesso</label>
                    <select class="form-control" disabled>
                        <option value="">-</option>
                        <?php foreach($roles as $role): ?>
                            <option value="<?php echo $role['uuid']; ?>" <?php echo ($entity['role_uuid'] == $role['uuid']) ? 'selected' : ''; ?>>
                                <?php echo $role['name']; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="phone">Telefone</label>
                    <input type="text" class="form-control" name="phone" id="phone" maxlength="13"
                        value="<?php echo $entity['phone']; ?>">
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="cellphone">Celular</label>
                    <input type="text" class="form-control" name="cellphone" id="cellphone" maxlength="14"
                        value="<?php echo $entity['cellphone']; ?>">
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="whatsapp">WhatsApp</label>
                    <input type="text" class="form-control" name="whatsapp" id="whatsapp" maxlength="14"
                        value="<?php echo $entity['whatsapp']; ?>">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Email</label>
                    <input type="email" class="form-control" name="email" id="email" required maxlength="100"
                        value="<?php echo $entity['email']; ?>">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="password">Nova senha</label>
                        <input type="password" class="form-control"name="password" maxlength="100">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="confirmation">Confirmar senha</label>
                    <input type="password" class="form-control" name="confirmation" maxlength="100">
                </div>
            </div>
            <div class="col-md-12 bg-primary mt-3 mb-3" style="border-radius: 5px;">
                <h4 class="pt-2 text-center">Localização</h4>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="postal_code">CEP</label>
                    <input type="text" class="form-control" name="postal_code" id="postal_code"  maxlength="9"
                        value="<?php echo $entity['postal_code']; ?>">
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="address">Endereço</label>
                    <input type="text" class="form-control" name="address" id="address"  maxlength="100"
                        value="<?php echo $entity['address']; ?>">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="number">Número</label>
                    <input type="text" class="form-control" name="number" id="number"  maxlength="50"
                        value="<?php echo $entity['number']; ?>">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="complement">Complemento</label>
                    <input type="text" class="form-control" name="complement" id="complement"  maxlength="50"
                        value="<?php echo $entity['complement']; ?>">
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label for="neighborhood">Bairro</label>
                    <input type="text" class="form-control" name="neighborhood" id="neighborhood"  maxlength="100"
                        value="<?php echo $entity['neighborhood']; ?>">
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label for="city">Cidade</label>
                    <input type="text" class="form-control" name="city" id="city"  maxlength="100"
                        value="<?php echo $entity['city']; ?>">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="state">UF</label>
                    <input type="text" class="form-control" name="state" id="state"  maxlength="2"
                        value="<?php echo $entity['state']; ?>">
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div class="col-md-4 offset-md-4 mt-3">
                <div class="form-group text-center">
                    <select name="status" id="status" class="form-control text-center" required>
                        <option value="1" <?php echo ($entity['status'] == '1') ? 'selected' : ''; ?>>Ativo no sistema</option>
                        <option value="0" <?php echo ($entity['status'] == '0') ? 'selected' : ''; ?>>Inativo no sistema</option>
                    </select>
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div class="col-md-4 text-center offset-md-4">
                <input type="hidden" name="uuid" value="<?php echo $entity['uuid']; ?>">
                <button type="submit" class="btn btn-success" style="width: 100%;">
                    <i class="fa fa-save pr-1"></i> Gravar
                </button>
            </div>
        </div>
    </form>
    <script src="<?php echo baseUrl; ?>public/js/api_cep.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/documents_validators.js"></script>
    <script>
        function hashPass(form) {
            if (form.password.value != '') {
                let psw = md5(form.password.value);
                form.password.value = psw;
            }

            if (form.confirmation.value != '') {
                let pswc = md5(form.confirmation.value);
                form.confirmation.value = pswc;
            }
        }
    </script>
    <script>
        $(document).ready(function() {
            $("#document_1").mask("999.999.999-99");
            $("#document_2").mask("99.999.999/9999-99");
            $("#postal_code").mask("99999-999");
            $("#phone").mask("(99)9999-9999");
            $("#cellphone").mask("(99)99999-9999");
            $("#whatsapp").mask("(99)99999-9999");

            $('#formUpdateUser').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "usuarios/valor-existente",
                            data: {uuid: '<?php echo $_POST['uuid']; ?>'}
                        }
                    },
                    email: {
                        remote: { 
                            type: "post",
                            url: "usuarios/valor-existente",
                            data: {uuid: '<?php echo $_POST['uuid']; ?>'}
                        }
                    },
                    cellphone: {
                        remote: { 
                            type: "post",
                            url: "usuarios/valor-existente",
                            data: {uuid: '<?php echo $_POST['uuid']; ?>'}
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nome já cadastrado"
                    },
                    email: {
                        remote: "Email já cadastrado"
                    },
                    cellphone: {
                        remote: "Celular já cadastrado"
                    }
                },
                submitHandler: function( form ){
                    var dados = $( form ).serialize();
                    $("#modalXLLoader").show();
                
                    $.ajax({
                        type: "POST",
                        url: "usuarios/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type == 'success') {
                            $("#modalXL").modal('hide');
                            openModule('usuarios');
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#modalXLLoader").hide();   
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>