<?php 
$entity = $this->view->entity; 
$roles = $this->view->roles; 
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 3, 1)): ?>
    <form method="post" name="formUpdateUser" id="formUpdateUser" onsubmit="hashPass(this);">
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" name="name" id="name" required
                        value="<?php echo $entity['name']; ?>">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="name">Status</label>
                    <select name="status" id="status" class="form-control" required>
                        <option value="1" <?php echo ($entity['status'] == '1') ? 'selected' : ''; ?>>Ativo</option>
                        <option value="0" <?php echo ($entity['status'] == '0') ? 'selected' : ''; ?>>Inativo</option>
                    </select>
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="name">Email</label>
                    <input type="email" class="form-control" name="email" id="email" required
                        value="<?php echo $entity['email']; ?>">
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="cellphone">Celular</label>
                    <input type="text" class="form-control" name="cellphone" id="cellphone"
                        value="<?php echo $entity['cellphone']; ?>">
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <label for="job_role">Cargo</label>
                    <input type="text" class="form-control" name="job_role" id="job_role" required
                        value="<?php echo $entity['job_role']; ?>">
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password">Nova senha</label>
                        <input type="password" class="form-control"name="password">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="confirmation">Confirmar senha</label>
                    <input type="password" class="form-control" name="confirmation">
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div class="col-md-4 text-center offset-md-4">
                <input type="hidden" name="id" value="<?php echo $entity['id']; ?>">
                <button type="submit" class="btn btn-success" style="width: 100%;">
                    <i class="fa fa-save pr-1"></i> Gravar
                </button>
            </div>
        </div>
    </form>
    <script src="<?php echo baseUrl; ?>public/js/md5.min.js"></script>
    <script>
        function hashPass(form) {
            if (form.password.value != '') {
                let psw = md5(form.password.value);
                form.password.value = psw;
            }

            if (form.confirmation.value != '') {
                let pswc = md5(form.confirmation.value);
                form.confirmation.value = pswc;
            }
        }
    </script>
    <script>
        $(document).ready(function(){
            $("#cellphone").mask("(99)99999-9999");

            $('#formUpdateUser').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "usuarios/valor-existente",
                            data: {id: '<?php echo $_POST['id']; ?>'}
                        }
                    },
                    email: {
                        remote: { 
                            type: "post",
                            url: "usuarios/valor-existente",
                            data: {id: '<?php echo $_POST['id']; ?>'}
                        }
                    },
                    cellphone: {
                        remote: { 
                            type: "post",
                            url: "usuarios/valor-existente",
                            data: {id: '<?php echo $_POST['id']; ?>'}
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nome já cadastrado"
                    },
                    email: {
                        remote: "Email já cadastrado"
                    },
                    cellphone: {
                        remote: "Celular já cadastrado"
                    }
                },
                submitHandler: function( form ){
                    var dados = $( form ).serialize();
                    $("#modalLargeLoader").show();
                
                    $.ajax({
                        type: "POST",
                        url: "usuarios/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        if (data.type == 'success') {
                            $("#modalLarge").modal('hide');
                            $("#modalLarge").modal('hide');
                            openModule('usuarios');
                        }
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#modalLargeLoader").hide();   
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>