<?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-6">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-plus-square pr-1"></i>
                        Adicionar Perfil
                    </h1>
                </div>
                <div class="col-6"></div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formCreateRole" id="formCreateRole">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            <label for="name">Nome</label>
                                            <input type="text" class="form-control" name="name" id="name" required>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="is_admin">Administrador?</label>
                                            <select name="is_admin" id="is_admin" class="form-control" required>
                                                <option value="0">Não</option>
                                                <option value="1">Sim</option>
                                                
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-right mt-3 mb-2">
                                        <button type="button" class="btn btn-default mr-3"
                                                onclick="openModule('controle-acesso');">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                        <button type="submit" class="btn btn-primary">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $('#formCreateRole').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>controle-acesso/valor-existente",
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nome já cadastrado"
                    },
                },
                submitHandler: function( form ){
                    var dados = $( form ).serialize();
                    
                    $("#baseLoader").show();
                    $("#btnSubmit").show('disabled', true);

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>controle-acesso/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        createRole();
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();
                        $("#btnSubmit").show('disabled', false); 
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>