<?php $data = $this->view->data; ?>
<?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-10">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-lock"></i>
                        Controle de Acesso
                    </h1>
                </div>
                <div class="col-2">
                    <ol class="breadcrumb float-right">
                        <li class="breadcrumb-item">
                            <button type="button" class="btn btn-primary btn-flat"
                                onclick="createRole();">
                                <i class="fas fa-plus pr-1"></i> Adicionar
                            </button>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="table_role" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center bg-primary">
                                            <th class="text-white" style="font-size: 14px;">Nome</th>
                                            <th class="text-white" style="font-size: 14px;">Administrador</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="cursor: pointer;" 
                                                onclick="openDetails('<?php echo $entity['uuid']; ?>');">
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['name']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo ($entity['is_admin'] == 1) ? 'Sim' : 'Não'; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data, row, column, node ) {
                            return data;
                        }
                    }
                }
            };	

            $('#table_role').DataTable({
                "sDom": 'flBtp',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'NÍVEIS DE ACESSO',
                        exportOptions: {columns: [0,1]}
                    })
                ],
                order: [ [0, "asc"] ],
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "_START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetails(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "controle-acesso/detalhes",
                data: {uuid:uuid},
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

        function rolePrivileges(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "controle-acesso/permissoes",
                data: {uuid:uuid},
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

        function createRole() {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "controle-acesso/cadastrar",
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

        function updateRole(uuid) {
            $("#baseLoader").show();
            $.ajax({
                type: 'post',
                url: "controle-acesso/editar",
                data: {uuid:uuid},
                async: true
            }).done(function(data) {
                $("#sis_content").html(data);
                $("#baseLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#baseLoader").hide();
            });
        }

        function deleteRole(uuid) {
            $("#modalLarge").modal('hide');
            $("#modalDeleteResult").empty();
            $("#modalDeleteTitle").html('<i class="fa fa-trash pr-2"></i> Perfil de Acesso');
            $("#modalDeleteLoader").hide();
            $("#modalDelete").modal('show');
            $("#modalDeleteResult").html('<button type="button" class="btn btn-default" onclick="runDelete(\''+uuid+'\');"><i class="fa fa-trash"></i> CONFIRMAR E EXCLUIR</button>');
        }   

        function runDelete(uuid) {
            if (uuid !== null || uuid !== undefined) {
                $("#modalDeleteLoader").show();

                $.ajax({
                    type: "POST",
                    url: "controle-acesso/excluir",
                    data: {uuid: uuid},
                    dataType: 'json',
                    async: true
                }).done(function(data) {
                    showAlert(data.type, data.title, data.msg, data.pos);
                    $("#modalDelete").modal('hide');
                    openModule('controle-acesso');
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalDeleteLoader").hide();
                });
            }
        }
    </script>
<?php endif; ?>