<?php $entity = $this->view->entity; ?>
<?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <label for="name">Nível:</label>
            <input type="text" class="form-control" readonly
                    value="<?php echo $entity['name']; ?>">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="name">Administrador:</label>
            <input type="text" class="form-control" readonly
                    value="<?php echo ($entity['is_admin']) ? 'Sim' : 'Não'; ?>">
        </div>
    </div>
    <div class="col-md-12"><hr></div>
    <div class="col-md-6 text-left">
        <span for="dt_cadastro">Cadastrado em:</span> <br>
        <b><?php echo $this->formatDateTime($entity['created_at']); ?></b>
    </div>
    <div class="col-md-6 text-right">
        <?php if (!empty($entity['updated_at'])): ?>
            <span for="dt_cadastro">Atualizado em:</span> <br>
            <b><?php echo $this->formatDateTime($entity['updated_at']); ?></b>
        <?php endif; ?>
    </div>
    <div class="col-md-12"><hr></div>
    <div class="col-3">
        <button type="button" class="btn btn-primary" onclick="updateRole('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
            <i class="fa fa-pen pr-1"></i> Editar
        </button>
    </div>
    <div class="col-6">
        <?php if ($entity['is_admin'] == 0): ?>
            <button type="button" class="btn btn-secondary" onclick="rolePrivileges('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                <i class="fa fa-unlock pr-1"></i> Permissões
            </button>
        <?php endif; ?>
    </div>
    <?php if ($entity['uuid'] != $_SESSION['COD'] && $entity['uuid'] != 1): ?>
        <div class="col-3 text-right">
            <button type="button" class="btn btn-danger" onclick="deleteRole('<?php echo $entity['uuid']; ?>');" style="width: 100%;">
                <i class="fa fa-trash"></i> Excluir
            </button>
        </div>
    <?php endif; ?>
</div>
<?php endif; ?>