<?php $entity = $this->view->entity; ?>
<?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
    <form method="post" name="formUpdateRole" id="formUpdateRole">
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label for="name">Nível</label>
                    <input type="text" class="form-control" name="name" id="name" required
                        value="<?php echo $entity['name']; ?>">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="name">Administrador</label>
                    <select name="is_admin" id="is_admin" class="form-control" required>
                        <option value="1" <?php echo ($entity['is_admin'] == '1') ? 'selected' : ''; ?>>Sim</option>
                        <option value="0" <?php echo ($entity['is_admin'] == '0') ? 'selected' : ''; ?>>Não</option>
                    </select>
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div class="col-md-4 text-center offset-md-4">
                <input type="hidden" name="uuid" value="<?php echo $entity['uuid']; ?>">
                <button type="submit" class="btn btn-success" style="width: 100%;">
                    <i class="fa fa-save pr-1"></i> Gravar
                </button>
            </div>
        </div>
    </form>
    <script>
        $(document).ready(function(){
            $('#formUpdateRole').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "controle-acesso/valor-existente",
                            data: {uuid: '<?php echo $_POST['uuid']; ?>'}
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nível já cadastrado"
                    },
                },
                submitHandler: function( form ){
                    var dados = $( form ).serialize();
                    $("#modalLargeLoader").show();
                
                    $.ajax({
                        type: "POST",
                        url: "controle-acesso/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalLarge").modal('hide');
                        $("#modalLarge").modal('hide');
                        openModule('controle-acesso');
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#modalLargeLoader").hide();   
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>