<?php $entity = $this->view->entity; ?>
<?php if ($_SESSION['ROLE_ADM'] == '1'): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-6">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-pen-square pr-1"></i>
                        Editar Perfil
                    </h1>
                </div>
                <div class="col-6"></div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateRole" id="formUpdateRole">
                                <div class="row">
                                    <div class="col-md-9">
                                        <div class="form-group">
                                            <label for="name">Nível</label>
                                            <input type="text" class="form-control" name="name" id="name" required
                                                value="<?php echo $entity['name']; ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="name">Administrador</label>
                                            <select name="is_admin" id="is_admin" class="form-control" required>
                                                <option value="1" <?php echo ($entity['is_admin'] == '1') ? 'selected' : ''; ?>>Sim</option>
                                                <option value="0" <?php echo ($entity['is_admin'] == '0') ? 'selected' : ''; ?>>Não</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-right mt-3 mb-2">
                                        <input type="hidden" name="uuid" value="<?php echo $entity['uuid']; ?>">
                                        <button type="button" class="btn btn-default mr-3"
                                                onclick="openModule('controle-acesso');">
                                            <i class="fas fa-arrow-left pr-1"></i> Voltar
                                        </button>
                                        <button type="submit" class="btn btn-primary">
                                            <i class="fa fa-save pr-1"></i> Salvar
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function(){
            $('#formUpdateRole').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "controle-acesso/valor-existente",
                            data: {uuid: '<?php echo $_POST['uuid']; ?>'}
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nível já cadastrado"
                    },
                },
                submitHandler: function( form ){
                    var dados = $( form ).serialize();
                    $("#baseLoader").show();
                
                    $.ajax({
                        type: "POST",
                        url: "controle-acesso/processa-edicao",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#baseLoader").hide();
                        openModule('controle-acesso');
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#baseLoader").hide();
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>