<?php 
$entity = $this->view->entity; 
$role = $_SESSION['ROLE'];

$canView    = ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('configs'))) ? true : false;
$canUpdate  = ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('configs'))) ? true : false;
?>
<?php if ($canView): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-12">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-cogs"></i>
                        Configurações
                    </h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" name="formUpdateConfig" id="formUpdateConfig"
                                enctype="multipart/form-data">
                                
                                
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Logo</label>
                                    <div class="col-sm-10">
                                            <?php if (!empty($entity['logo'])): ?>
                                                <div class="mb-3">
                                                    <a href="<?php echo baseUrl . 'public/uploads/logo/'
                                                        . $entity['logo']; ?>" target="_blank">
                                                        <img src="<?php echo baseUrl . 'public/uploads/logo/'
                                                            . $entity['logo']; ?>" alt="" style="width: 20%;">
                                                    </a>
                                                </div>
                                            <?php endif; ?>
                                        <input type="file" class="form-control" name="logo" id="logo">
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Ícone</label>
                                    <div class="col-sm-10">
                                            <?php if (!empty($entity['logo_icon'])): ?>
                                                <div class="mb-3">
                                                    <a href="<?php echo baseUrl . 'public/uploads/logo/'
                                                        . $entity['logo_icon']; ?>" target="_blank">
                                                        <img src="<?php echo baseUrl . 'public/uploads/logo/'
                                                            . $entity['logo_icon']; ?>" alt="" style="width: 10%;">
                                                    </a>
                                                </div>
                                            <?php endif; ?>
                                        <input type="file" class="form-control" name="logo_icon" id="logo_icon">
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Título</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="site_title" id="site_title"
                                            value="<?php echo $entity['site_title']; ?>" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Cor Primária</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="primary_color" id="primary_color"
                                            value="<?php echo $entity['primary_color']; ?>" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Cor Secundária</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="secondary_color" id="secondary_color"
                                            value="<?php echo $entity['secondary_color']; ?>" required>
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Email</label>
                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" name="email" id="email" required
                                            value="<?php echo $entity['email']; ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Telefone</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="phone" id="phone"
                                            value="<?php echo $entity['phone']; ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Celular (Whatsapp)</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="cellphone" id="cellphone" required
                                            value="<?php echo $entity['cellphone']; ?>">
                                    </div>
                                </div>
                                <div class="form-group"><hr></div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Endereço completo</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="full_address" id="full_address"
                                            value="<?php echo $entity['full_address']; ?>">
                                    </div>
                                </div>
                                <div class="form-group"><hr></div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Servidor SMTP</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mail_host" id="mail_host"
                                            value="<?php echo $entity['mail_host']; ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Porta</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mail_port" id="mail_port"
                                            value="<?php echo $entity['mail_port']; ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Usuário</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mail_username" id="mail_username"
                                            value="<?php echo $entity['mail_username']; ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Senha</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mail_password" id="mail_password">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Email para envio</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mail_from_address" id="mail_from_address"
                                            value="<?php echo $entity['mail_from_address']; ?>">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="default-input" class="col-sm-2 form-control-label">Email para Recebimento</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mail_to_address" id="mail_to_address"
                                            value="<?php echo $entity['mail_to_address']; ?>">
                                    </div>
                                </div>
                                <?php if ($canUpdate): ?>
                                    <div class="col-md-12"><hr></div>
                                    <div class="col-md-4 text-center offset-md-4">
                                        <button type="submit" class="btn btn-success" style="width: 100%;" id="btnSubmit">
                                            <i class="fa fa-save pr-1"></i> Gravar
                                        </button>
                                    </div>
                                <?php endif; ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php if ($canUpdate): ?>
        <script>
            $(document).ready(function(){
                $("#phone").mask("(99)9999-9999");
                $("#cellphone").mask("(99)99999-9999");

                $('#formUpdateConfig').validate({
                    submitHandler: function( form ){
                        let dados = $( form ).serialize();
                        let logo = $('#logo').prop('files')[0];   
                        let logo_icon = $('#logo_icon').prop('files')[0];   
                        let form_data = new FormData();     
                        
                        form_data.append('uuid', '<?php echo $entity['uuid']; ?>');
                        form_data.append('site_title', $("#site_title").val());
                        form_data.append('email', $("#email").val());
                        form_data.append('phone', $("#phone").val());
                        form_data.append('cellphone', $("#cellphone").val());
                        form_data.append('full_address', $("#full_address").val());
                       
                        form_data.append('mail_host', $("#mail_host").val());
                        form_data.append('mail_port', $("#mail_port").val());
                        form_data.append('mail_username', $("#mail_username").val());
                        form_data.append('mail_password', $("#mail_password").val());
                        form_data.append('mail_from_address', $("#mail_from_address").val());
                        form_data.append('mail_to_address', $("#mail_to_address").val());

                        form_data.append('primary_color', $("#primary_color").val());
                        form_data.append('secondary_color', $("#secondary_color").val());

                        form_data.append('logo', logo);    
                        form_data.append('logo_icon', logo_icon);    

                        $("#baseLoader").show();
                        $("#btnSubmit").show('disabled', true);

                        $.ajax({
                            type: "POST",
                            url: "configuracoes/processa-edicao",
                            cache: false,
                            contentType: false,
                            processData: false,
                            data: form_data,
                            dataType: 'json',
                            async: true
                        }).done(function(data) {
                            showAlert(data.type, data.title, data.msg, data.pos);
                            $("#baseLoader").hide();
                            openModule('configuracoes');
                        }).fail(function() {
                            showInternalErrorAlert(); 
                            $("#baseLoader").hide();   
                            $("#btnSubmit").show('disabled', false);
                        }); 

                        return false;
                    }
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>