<?php
$role = $_SESSION['ROLE'];
?>
<?php if ($_SESSION['ROLE_ADM'] == '1' || $this->acl($role, $this->resourceCodes('create'), $this->moduleCodes('customers'))): ?>
    <form method="post" name="formCreateCustomer" id="formCreateCustomer">
        <div class="row">
            <div class="col-md-12 bg-primary mb-3" style="border-radius: 5px;">
                <h4 class="pt-2 text-center">Dados Pessoais</h4>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" name="name" id="name" required maxlength="200">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="cnpj">CPF</label>
                    <input type="text" class="form-control" name="document_1" id="document_1"  maxlength="14" onchange="validateCPF();">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="cnpj">CNPJ</label>
                    <input type="text" class="form-control" name="document_2" id="document_2"  maxlength="18" onchange="validateCNPJ();">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="contato">Email</label>
                    <input type="email" class="form-control" name="email" id="email" maxlength="100" required>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="phone">Telefone</label>
                    <input type="text" class="form-control" name="phone" id="phone" maxlength="13">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="cellphone">Celular</label>
                    <input type="text" class="form-control" name="cellphone" id="cellphone" maxlength="14">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="whatsapp">WhastApp</label>
                    <input type="text" class="form-control" name="whatsapp" id="whatsapp" maxlength="14">
                </div>
            </div>
            <div class="col-md-12 bg-primary mt-3 mb-3" style="border-radius: 5px;">
                <h4 class="pt-2 text-center">Localização</h4>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="postal_code">CEP</label>
                    <input type="text" class="form-control" name="postal_code" id="postal_code"  maxlength="9">
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="address">Endereço</label>
                    <input type="text" class="form-control" name="address" id="address"  maxlength="100">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="number">Número</label>
                    <input type="text" class="form-control" name="number" id="number"  maxlength="50">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="complement">Complemento</label>
                    <input type="text" class="form-control" name="complement" id="complement"  maxlength="50">
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label for="neighborhood">Bairro</label>
                    <input type="text" class="form-control" name="neighborhood" id="neighborhood"  maxlength="100">
                </div>
            </div>
            <div class="col-md-5">
                <div class="form-group">
                    <label for="city">Cidade</label>
                    <input type="text" class="form-control" name="city" id="city"  maxlength="100">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="state">UF</label>
                    <input type="text" class="form-control" name="state" id="state"  maxlength="2">
                </div>
            </div>
            <div class="col-md-12"><hr></div>
            <div class="col-md-4 text-center offset-md-4">
                <button type="submit" class="btn btn-success" style="width: 100%;">
                    <i class="fa fa-save pr-1"></i> Gravar
                </button>
            </div>
        </div>
    </form>
    <script src="<?php echo baseUrl; ?>public/js/api_cep.js"></script>
    <script src="<?php echo baseUrl; ?>public/js/documents_validators.js"></script>
    <script>
        $(document).ready(function(){
            $("#name").focus();
            $("#postal_code").mask("99999-999");
            $("#document_1").mask("999.999.999-99");
            $("#document_2").mask("99.999.999/9999-99");
            $("#phone").mask("(99)9999-9999");
            $("#cellphone").mask("(99)99999-9999");
            $("#whatsapp").mask("(99)99999-9999");

            $('#formCreateCustomer').validate({
                rules: {
                    name: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>clientes/valor-existente",
                        }
                    },
                    cnpj: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>clientes/valor-existente",
                        }
                    },
                    document_1: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>clientes/valor-existente",
                        }
                    },
                    document_2: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>clientes/valor-existente",
                        }
                    },
                    email: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>clientes/valor-existente",
                        }
                    },
                    cellphone: {
                        remote: { 
                            type: "post",
                            url: "<?php echo baseUrl; ?>clientes/valor-existente",
                        }
                    },
                },
                messages: {
                    name: {
                        remote: "Nome já cadastrado"
                    },
                    document_1: {
                        remote: "CPF já cadastrado"
                    },
                    document_2: {
                        remote: "CNPJ já cadastrado"
                    },
                    email: {
                        remote: "Email já cadastrado"
                    },
                    cellphone: {
                        remote: "Celular já cadastrado"
                    },
                },
                submitHandler: function( form ){
                    var dados = $( form ).serialize();
                    $("#modalXLLoader").show();

                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>clientes/processa-cadastro",
                        data: dados,
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalXL").modal('hide');
                        openModule('clientes');
                    }).fail(function() {
                        showInternalErrorAlert(); 
                        $("#modalXLLoader").hide();   
                    }); 

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>