<?php 
$data = $this->view->data; 

$canView    = ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 1, 6)) ? true : false;
$canCreate  = ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 2, 6)) ? true : false;
$canUpdate  = ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 3, 6)) ? true : false;
$canDelete  = ($_SESSION['ROLE_ADM'] == '1' || $this->acl($_SESSION['ROLE'], 4, 6)) ? true : false;
?>
<?php if ($canView): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-6">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-users"></i>
                        Clientes
                    </h1>
                </div>
                <div class="col-6">
                    <?php if ($canCreate): ?>
                        <ol class="breadcrumb float-right">
                            <li class="breadcrumb-item">
                                <button type="button" class="btn btn-primary btn-flat"
                                    onclick="createCustomer();">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </li>
                        </ol>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover" id="tbl_prioridade" style="width: 99.9%;">
                                    <thead>
                                        <tr class="text-center bg-primary" style="height: 30px;">
                                            <th class="text-white" style="font-size: 14px;">Nome</th>
                                            <th class="text-white" style="font-size: 14px;">Email</th>
                                            <th class="text-white" style="font-size: 14px;">Telefone</th>
                                            <th class="text-white" style="font-size: 14px;">Celular</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($data as $entity): ?>
                                            <tr class="text-center" style="height: 30px; cursor: pointer;" 
                                                onclick="openDetailsCustomer(<?php echo $entity['id']; ?>);">
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['name']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['email']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['phone']; ?>
                                                </td>
                                                <td style="font-size: 15px">
                                                    <?php echo $entity['cellphone']; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script type="text/javascript">
        $(document).ready(function() {
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function ( data, row, column, node ) {
                            // Formatando números para que sejam mostrados no excel corretamente
                            return  data;
                        }
                    }
                }
            };	

            $('#tbl_prioridade').DataTable({
                "sDom": 'flBtip',
                searching: true,
                buttons: [
                    $.extend( true, {}, buttonCommon, {
                        extend: 'excel',
                        title: 'CLIENTES',
                        exportOptions: {columns: [0,1,2,3]}
                    }),
                ],
                order: [ [0, "asc"] ],
               
                responsive: true,
                info: true,
                processing: true,
                scrollCollapse: true,
                paging: true,
                "pageLength": 25,
                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ &nbsp;",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Filtrar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                }
            });
        });

        function openDetailsCustomer(id) {
            $("#modalXLResult").empty();
            $("#modalXLTitle").html('<i class="fa fa-users"></i> Dados do Cliente');
            $("#modalXLLoader").show();
            $("#modalXL").modal('show');

            $.ajax({
                type: 'post',
                url: "<?php echo baseUrl; ?>clientes/detalhes",
                data: {id:id},
                async: true
            }).done(function(data) {
                $("#modalXLResult").html(data);
                $("#modalXLLoader").hide();
            }).fail(function() {
                showInternalErrorAlert();
                $("#modalXLLoader").hide();
            });
        }

    </script>
    <?php if ($canCreate): ?>
        <script>
            function createCustomer() {
                $("#modalXLResult").empty();
                $("#modalXLTitle").html('<i class="fa fa-users"></i> Novo Cliente');
                $("#modalXLLoader").show();
                $("#modalXL").modal('show');

                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>clientes/cadastrar",
                    async: true
                }).done(function(data) {
                    $("#modalXLResult").html(data);
                    $("#modalXLLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalXLLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canUpdate): ?>
        <script>
            function updateCustomer(id) {
                $("#modalXLResult").empty();
                $("#modalXLTitle").html('<i class="fa fa-users"></i> Editar Cliente');
                $("#modalXLLoader").show();
                $("#modalXL").modal('show');

                $.ajax({
                    type: 'post',
                    url: "<?php echo baseUrl; ?>clientes/editar",
                    data: {id:id},
                    async: true
                }).done(function(data) {
                    $("#modalXLResult").html(data);
                    $("#modalXLLoader").hide();
                }).fail(function() {
                    showInternalErrorAlert();
                    $("#modalXLLoader").hide();
                });
            }
        </script>
    <?php endif; ?>
    <?php if ($canDelete): ?>
        <script>
            function deleteCustomer(id) {
                a = confirm("Deseja remover este Cliente?");
                if (a) {
                    $("#modalXLLoader").show();
                    
                    $.ajax({
                        type: "POST",
                        url: "<?php echo baseUrl; ?>clientes/excluir",
                        data: {id: id},
                        dataType: 'json',
                        async: true
                    }).done(function(data) {
                        showAlert(data.type, data.title, data.msg, data.pos);
                        $("#modalXL").modal('hide');
                        openModule('clientes');
                    }).fail(function() {
                        showInternalErrorAlert();
                        $("#modalXLLoader").hide();
                    });
                } else {
                    return false;
                }	
            }
        </script>
    <?php endif; ?>
<?php endif; ?>