<?php 
$entity = $this->view->entity; 

$isAdmin = ($_SESSION['ROLE_ADM'] == '1') ? true : false;
$role    = $_SESSION['ROLE'];

$canView    = ($isAdmin || $this->acl($role, $this->resourceCodes('view'), $this->moduleCodes('customers'))) ? true : false;
$canUpdate  = ($isAdmin || $this->acl($role, $this->resourceCodes('update'), $this->moduleCodes('customers'))) ? true : false;
$canDelete  = ($isAdmin || $this->acl($role, $this->resourceCodes('delete'), $this->moduleCodes('customers'))) ? true : false;
?>
<?php if ($canView): ?>
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-6">
                    <h1 style="position: relative; top: 5px">
                        <i class="fas fa-info-circle pr-1"></i>
                        Dados de Cadastro
                    </h1>
                </div>
                <div class="col-6"></div>
            </div>
        </div>
    </section>
    <section class="content" style="margin-left: 9px; margin-right: 9px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12" style="border-radius: 5px;">
                                    <h5 class="pt-2"><i class="fas fa-user pr-1"></i> Dados Pessoais</h5>
                                    <hr>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="nome">Nome</label>
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo $entity['name']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cnpj">CPF</label>
                                        <input type="text" class="form-control" readonly 
                                               value="<?php echo $this->inputMasked($entity['document_1'], '###.###.###-##'); ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cnpj">CNPJ</label>
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo $this->inputMasked($entity['document_2'], '##.###.###/####-##'); ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="contato">Email</label>
                                        <input type="email" class="form-control" readonly
                                               value="<?php echo $entity['email']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="phone">Telefone</label>
                                        <input type="text" class="form-control" readonly 
                                               value="<?php echo $this->inputMasked($entity['phone'], '(##) ####-####'); ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="cellphone">Celular</label>
                                        <input type="text" class="form-control" readonly 
                                               value="<?php echo $this->inputMasked($entity['cellphone'], '(##) #####-####'); ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="whatsapp">WhastApp</label>
                                        <input type="text" class="form-control" readonly 
                                               value="<?php echo $this->inputMasked($entity['whatsapp'], '(##) #####-####'); ?>">
                                    </div>
                                </div>
                                <div class="col-md-12" style="border-radius: 5px;">
                                    <h5 class="pt-2"><i class="fas fa-map-marker-alt pr-1"></i> Localização</h5>
                                    <hr>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="postal_code">CEP</label>
                                        <input type="text" class="form-control"  readonly 
                                               value="<?php echo $this->inputMasked($entity['postal_code'], '#####-###'); ?>">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="address">Endereço</label>
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo $entity['address']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="number">Número</label>
                                        <input type="text" class="form-control"  readonly
                                               value="<?php echo $entity['number']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="complement">Complemento</label>
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo $entity['complement']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label for="neighborhood">Bairro</label>
                                        <input type="text" class="form-control"  readonly
                                               value="<?php echo $entity['neighborhood']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label for="city">Cidade</label>
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo $entity['city']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="state">UF</label>
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo $entity['state']; ?>">
                                    </div>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-6 col-md-3">
                                    <span for="dt_cadastro">Status</span> <br>
                                    <b><?php echo ($entity['status'] == '1') ? 'Ativo' : 'Inativo'; ?></b>
                                </div>
                                <div class="col-6 col-md-3">
                                    <span for="dt_cadastro">Cadastro em:</span> <br>
                                    <b><?php echo $this->formatDateTime($entity['created_at']); ?></b>
                                </div>
                                <div class="col-6 col-md-3">
                                    <?php if (!empty($entity['updated_at'])): ?>
                                        <span for="dt_cadastro">Atualizado em:</span> <br>
                                        <b><?php echo $this->formatDateTime($entity['updated_at']); ?></b>
                                    <?php endif; ?>
                                </div>
                                <div class="col-6 col-md-3">
                                    <span for="dt_cadastro">Cadastrado por:</span> <br>
                                    <b><?php echo $entity['username']; ?></b>
                                </div>
                                <div class="col-md-12"><hr></div>
                                <div class="col-4 col-md-3 mt-3 mb-2">
                                    <?php if ($canDelete): ?>
                                        <button type="button" class="btn btn-default" onclick="deleteCustomer('<?php echo $entity['uuid']; ?>');">
                                            <i class="fa fa-trash"></i> Remover
                                        </button>
                                    <?php endif; ?>
                                </div>
                                <div class="col-8 col-md-9 text-right mt-3 mb-2">
                                    <button type="button" class="btn btn-default mr-2"
                                            onclick="openModule('clientes');">
                                        <i class="fas fa-arrow-left pr-1"></i> Voltar
                                    </button>
                                    <?php if ($canUpdate): ?>
                                        <button type="button" class="btn btn-primary" onclick="updateCustomer('<?php echo $entity['uuid']; ?>');">
                                            <i class="fa fa-pen pr-1"></i> Editar
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>